config/routes.rb
Rails.application.routes.draw do
  get '/calendar', to: 'pages#home'
  resources :bookings
  root to: 'bookings#index'
  get '/eolo-bookings', to: 'bookings#index_eolo'
  get '/barqa-bookings', to: 'bookings#index_barqa'
  get '/facturas', to: 'bookings#facturas', as: 'facturas'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord

  def self.total_eolo
    total = 0
    Booking.all.each do |booking|
      if booking.barco == "eolo" && booking.preunet != nil
         total = total + booking.preunet
      end
    end
    return total
  end

  def self.total_barqa
    total = 0
    Booking.all.each do |booking|
      if booking.barco == "barqa" && booking.preunet != nil
        total = total + booking.preunet
      end
    end
    return total
  end

  def self.total
    return Booking.total_barqa + Booking.total_eolo
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[ show edit update destroy ]

  def index
    @q = Booking.ransack(params[:q])
    @q.sorts = "fecha_inicio asc" if @q.sorts.empty?
    @bookings = @q.result(distinct: true)
  end

  # GET /bookings or /bookings.json
  def index_eolo
    # @bookings = Booking.where(barco: "eolo")
    @q = Booking.where(barco: "eolo").ransack(params[:q])
    @q.sorts = "fecha_inicio asc" if @q.sorts.empty?
    @bookings = @q.result(distinct: true)
  end

  def index_barqa
    # @bookings = Booking.where(barco: "barqa")
    @q = Booking.where(barco: "barqa").ransack(params[:q])
    @q.sorts = "fecha_inicio asc" if @q.sorts.empty?
    @bookings = @q.result(distinct: true)
  end

  # GET /bookings/1 or /bookings/1.json
  def show
  end

  # GET /bookings/new
  def new
    @booking = Booking.new
  end

  # GET /bookings/1/edit
  def edit
  end





  def facturas
    @bookings = Booking.where(canal: "Nautal").or(Booking.where(canal: "Click&Boat")).or(Booking.where(canal: "Samboat")).order(fecha_inicio: :asc)
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "facturas",
        template: "bookings/facturas.html.erb",
        encoding: 'utf8'
      end
    end
  end










  # POST /bookings or /bookings.json
  def create
    @booking = Booking.new(booking_params)

    respond_to do |format|
      if @booking.save
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully created." }
        format.json { render :show, status: :created, location: @booking }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookings/1 or /bookings/1.json
  def update
    respond_to do |format|
      if @booking.update(booking_params)
        format.html { redirect_to booking_url(@booking), notice: "Booking was successfully updated." }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1 or /bookings/1.json
  def destroy
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url, notice: "Booking was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def booking_params
      params.require(:booking).permit(:fecha_inicio, :fecha_final, :barco, :nom, :contacte, :preu, :canal, :observacions, :preunet)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<%= simple_form_for(@booking) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :fecha_inicio, html5: true %>
    <%= f.input :fecha_final, html5: true %>
    <%= f.input :barco,
            as: :radio_buttons,
            collection: ["eolo", "barqa"] %>
    <%= f.input :nom %>
    <%= f.input :contacte %>
    <%= f.input :preu %>
    <%= f.input :canal,
            as: :radio_buttons,
            collection: ["Click&Boat", "Nautal", "Wallapop", "Samboat", "Whatsapp", "Altres"] %>
    <%= f.input :preunet %>
    <%= f.input :observacions %>
  </div>

  <div class="form-actions text-center">
    <%= f.button :submit, class:"btn btn-primary" %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<h1>Editar la reserva</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/facturas.html.erb
<%i = 0 %>
<% @bookings.each do |booking|%>
  <%i += 1 %>
  <div style="border-top: 1px solid gray; padding-bottom: 30px; margin-bottom: 30px;">
    <table style="width:100%">
      <tr>
        <td>
          MARTÍ GIRÓ CORCOLL
        </td>
        <td>
          <p style="text-align:right; font-family: Arial, Helvetica, sans-serif;">Martí Giró Corcoll - 41559928d</p>
          <p style="text-align:right; font-family: Arial, Helvetica, sans-serif;">Pg. Joan de Borbó 103 L11</p>
          <p style="text-align:right; font-family: Arial, Helvetica, sans-serif;">Barcelona 08039</p>
        </td>
      </tr>
    </table>
  </div>
  <div style="border-bottom: 0px solid gray; font-family: Arial, Helvetica, sans-serif; padding-bottom: 30px; margin-bottom: 30px;">
    <table style="width:100%">
      <td>
        <h2 style= "font-family: Arial, Helvetica, sans-serif;"><%= "Factura: B220#{i}" %></h2>
      </td>
      <td>
      <h2 style="text-align:right;">Fecha: <small><%= booking.fecha_inicio.strftime("%d-%m-%Y") %></small></h2>
      </td>
    </table>
    <table style="width:100%">
      <td>
        <h3>
          <strong>Cliente:</strong>
          <strong><%= booking.nom %></strong>
        </h3>
      </td>
      <td>
        <h1 style = "text-align:right;">Total: <%= booking.preu%> €</h1>
      </td>
    </table>

    <p>
      <strong>Contacto:</strong>
      <%= booking.contacte %>
    </p>

    <p>
      <strong>Embarcación:</strong>
      <%= booking.barco %>
    </p>
  </div>
  <div style="border-bottom: 1px solid gray; font-family: Arial, Helvetica, sans-serif; padding-bottom: 30px; margin-bottom: 30px;">
    <table style = "width: 100%;">
      <tr>
        <td>
          <h2>Concepto</h2>
        </td>
        <td style="text-align:right;">
          <h2>Precio</h2>
        </td>
        <td style="text-align:right;">
          <h2>IVA</h2>
        </td>
        <td style="text-align:right;">
          <h2>Total</h2>
        </td>
      </tr>
      <tr>
        <td>
          <h3><strong>Alquiler del barco: <%=   booking.barco %></strong></h3>
        </td>
        <td style="text-align:right;">
            <p>
              <%= number_to_currency(booking.preu.to_i / (1.21))[1..].gsub(",",":").gsub(".",",").gsub(":",".")  %>€
            </p>
        </td>
        <td style="text-align:right;">
              <p>
              <%= number_to_currency(booking.preu.to_i / (1.21)*0.21)[1..].gsub(",",":").gsub(".",",").gsub(":",".")  %>€

              </p>
        </td>
        <td style="text-align:right;">
          <p>
            <%= booking.preu %>€
          </p>
        </td>
      </tr>
      <tr>
        <td>
          <p><strong>Inicio:</strong> <%= booking.fecha_inicio.strftime("%d-%m-%Y") %></p>
          <p><strong>Final:</strong> <%= booking.fecha_final.strftime("%d-%m-%Y") %></p>
        </td>
      </tr>

    </table>
  </div>
  <div class="page-break"></div>

<% end %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas</h1>

<table class="table">
  <thead>
    <tr>
      <th> <%= sort_link(@q, :fecha_inicio, 'Fecha inicio', default_order: :desc) %></th>
      <th>Fecha final</th>
      <th>Barco</th>
      <th>Nom</th>
      <th>Canal</th>
      <th><%= Booking.total %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
    <tr>
      <% if booking.fecha_inicio < Date.today() %>
        <td style = "background-color: gray;"><%= link_to booking.fecha_inicio.strftime("%d-%m-%Y"), booking %></td>
      <% else %>
        <td><%= link_to booking.fecha_inicio.strftime("%d-%m-%Y"), booking %></td>
      <% end %>
        <td><%= booking.fecha_final %></td>
        <td><%= booking.barco %></td>
        <td><%= booking.nom %></td>
        <td><%= booking.canal %></td>
        <td><%= booking.preunet %>€</td>
        <td><%= link_to 'x', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/index_barqa.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas barqa</h1>

<table class="table">
  <thead>
    <tr>
      <th> <%= sort_link(@q, :fecha_inicio, 'Fecha inicio', default_order: :desc) %></th>
      <th>Fecha final</th>
      <th>Barco</th>
      <th>Nom</th>
      <th>Contacte</th>
      <th><%= Booking.total_barqa %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
      <% if booking.fecha_inicio < Date.today() %>
        <td style = "background-color: gray;"><%= link_to booking.fecha_inicio.strftime("%d-%m-%Y"), booking %></td>
      <% else %>
        <td><%= link_to booking.fecha_inicio.strftime("%d-%m-%Y"), booking %></td>
      <% end %>
        <td><%= booking.fecha_final %></td>
        <td><%= booking.barco %></td>
        <td><%= booking.nom %></td>
        <td><%= booking.contacte %></td>
        <td><%= booking.preunet %>€</td>
        <td><%= link_to 'x', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/index_eolo.html.erb
<p id="notice"><%= notice %></p>

<h1>Reservas eolo</h1>

<table class="table">
  <thead>
    <tr>
      <th> <%= sort_link(@q, :fecha_inicio, 'Fecha inicio', default_order: :desc) %></th>
      <th>Fecha final</th>
      <th>Barco</th>
      <th>Nom</th>
      <th>Contacte</th>
      <th><%= Booking.total_eolo %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @bookings.each do |booking| %>
      <tr>
      <% if booking.fecha_inicio < Date.today() %>
        <td style = "background-color: gray;"><%= link_to booking.fecha_inicio.strftime("%d-%m-%Y"), booking %></td>
      <% else %>
        <td><%= link_to booking.fecha_inicio.strftime("%d-%m-%Y"), booking %></td>
      <% end %>
        <td><%= booking.fecha_final %></td>
        <td><%= booking.barco %></td>
        <td><%= booking.nom %></td>
        <td><%= booking.contacte %></td>
        <td><%= booking.preunet %>€</td>
        <td><%= link_to 'x', booking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/bookings/new.html.erb
<h1>Nueva reserva</h1>

<%= render 'form', booking: @booking %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fecha inicio:</strong>
  <%= @booking.fecha_inicio %>
</p>

<p>
  <strong>Fecha final:</strong>
  <%= @booking.fecha_final %>
</p>

<p>
  <strong>Barco:</strong>
  <%= @booking.barco %>
</p>

<p>
  <strong>Nom:</strong>
  <%= @booking.nom %>
</p>

<p>
  <strong>Contacte:</strong>
  <%= @booking.contacte %>
</p>

<p>
  <strong>Preu:</strong>
  <%= @booking.preu %>
</p>

<p>
  <strong>Preu net:</strong>
  <%= @booking.preunet %>
</p>

<p>
  <strong>Canal:</strong>
  <%= @booking.canal %>
</p>

<p>
  <strong>Observacions:</strong>
  <%= @booking.observacions %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BoatBooking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <div class= "text-center">
    <table class="table">
      <thead>
        <tr>
          <th><%= link_to 'Calendari', calendar_path, class: "btn btn-success" %></th>
          <th>  </th>
          <th><%= link_to 'Todas las reservas', bookings_path, class: "btn btn-secondary" %></th>
          <th><%= link_to 'Barqa', barqa_bookings_path, class: "btn btn-secondary" %></th>
          <th><%= link_to 'Eolo', eolo_bookings_path, class: "btn btn-secondary" %></th>
          <th>  </th>
          <th><%= link_to '+', new_booking_path, class: "btn btn-primary" %></th>
        </tr>
      </thead>
    </table>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<p align="center">
  <iframe src="https://calendar.google.com/calendar/embed?height=600&wkst=2&bgcolor=%23ffffff&ctz=Europe%2FMadrid&mode=MONTH&showPrint=0&showTabs=1&showTz=0&showNav=1&showTitle=0&src=ZmFjdHVyYXNpbXBvcnR5QGdtYWlsLmNvbQ&src=OGxoNmJvamNxa3ZyZjh1bjNxcTRyZ2FxZHNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&color=%2350a7ad&color=%23C0CA33" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</p>